const elements = [
    { id: 1, symbol: 'H', name: 'Hydrogen', atomicNumber: 1, mass: 1.008, category: 'nonmetal', period: 1, group: 1 },
    { id: 2, symbol: 'He', name: 'Helium', atomicNumber: 2, mass: 4.003, category: 'noble-gas', period: 1, group: 18 },
    { id: 3, symbol: 'Li', name: 'Lithium', atomicNumber: 3, mass: 6.941, category: 'metal', period: 2, group: 1 },
    { id: 4, symbol: 'Be', name: 'Beryllium', atomicNumber: 4, mass: 9.012, category: 'metal', period: 2, group: 2 },
    { id: 5, symbol: 'B', name: 'Boron', atomicNumber: 5, mass: 10.811, category: 'nonmetal', period: 2, group: 13 },
    { id: 6, symbol: 'C', name: 'Carbon', atomicNumber: 6, mass: 12.011, category: 'nonmetal', period: 2, group: 14 },
    { id: 7, symbol: 'N', name: 'Nitrogen', atomicNumber: 7, mass: 14.007, category: 'nonmetal', period: 2, group: 15 },
    { id: 8, symbol: 'O', name: 'Oxygen', atomicNumber: 8, mass: 15.999, category: 'nonmetal', period: 2, group: 16 },
    { id: 9, symbol: 'F', name: 'Fluorine', atomicNumber: 9, mass: 18.998, category: 'nonmetal', period: 2, group: 17 },
    { id: 10, symbol: 'Ne', name: 'Neon', atomicNumber: 10, mass: 20.180, category: 'noble-gas', period: 2, group: 18 },
    { id: 11, symbol: 'Na', name: 'Sodium', atomicNumber: 11, mass: 22.990, category: 'metal', period: 3, group: 1 },
    { id: 12, symbol: 'Mg', name: 'Magnesium', atomicNumber: 12, mass: 24.305, category: 'metal', period: 3, group: 2 },
    { id: 13, symbol: 'Al', name: 'Aluminum', atomicNumber: 13, mass: 26.982, category: 'metal', period: 3, group: 13 },
    { id: 14, symbol: 'Si', name: 'Silicon', atomicNumber: 14, mass: 28.086, category: 'nonmetal', period: 3, group: 14 },
    { id: 15, symbol: 'P', name: 'Phosphorus', atomicNumber: 15, mass: 30.974, category: 'nonmetal', period: 3, group: 15 },
    { id: 16, symbol: 'S', name: 'Sulfur', atomicNumber: 16, mass: 32.065, category: 'nonmetal', period: 3, group: 16 },
    { id: 17, symbol: 'Cl', name: 'Chlorine', atomicNumber: 17, mass: 35.453, category: 'nonmetal', period: 3, group: 17 },
    { id: 18, symbol: 'Ar', name: 'Argon', atomicNumber: 18, mass: 39.948, category: 'noble-gas', period: 3, group: 18 },
    { id: 19, symbol: 'K', name: 'Potassium', atomicNumber: 19, mass: 39.098, category: 'metal', period: 4, group: 1 },
    { id: 20, symbol: 'Ca', name: 'Calcium', atomicNumber: 20, mass: 40.078, category: 'metal', period: 4, group: 2 },
    { id: 21, symbol: 'Sc', name: 'Scandium', atomicNumber: 21, mass: 44.956, category: 'transition-metal', period: 4, group: 3 },
    { id: 22, symbol: 'Ti', name: 'Titanium', atomicNumber: 22, mass: 47.867, category: 'transition-metal', period: 4, group: 4 },
    { id: 23, symbol: 'V', name: 'Vanadium', atomicNumber: 23, mass: 50.942, category: 'transition-metal', period: 4, group: 5 },
    { id: 24, symbol: 'Cr', name: 'Chromium', atomicNumber: 24, mass: 51.996, category: 'transition-metal', period: 4, group: 6 },
    { id: 25, symbol: 'Mn', name: 'Manganese', atomicNumber: 25, mass: 54.938, category: 'transition-metal', period: 4, group: 7 },
    { id: 26, symbol: 'Fe', name: 'Iron', atomicNumber: 26, mass: 55.845, category: 'transition-metal', period: 4, group: 8 },
    { id: 27, symbol: 'Co', name: 'Cobalt', atomicNumber: 27, mass: 58.933, category: 'transition-metal', period: 4, group: 9 },
    { id: 28, symbol: 'Ni', name: 'Nickel', atomicNumber: 28, mass: 58.693, category: 'transition-metal', period: 4, group: 10 },
    { id: 29, symbol: 'Cu', name: 'Copper', atomicNumber: 29, mass: 63.546, category: 'transition-metal', period: 4, group: 11 },
    { id: 30, symbol: 'Zn', name: 'Zinc', atomicNumber: 30, mass: 65.409, category: 'transition-metal', period: 4, group: 12 },
    { id: 31, symbol: 'Ga', name: 'Gallium', atomicNumber: 31, mass: 69.723, category: 'metal', period: 4, group: 13 },
    { id: 32, symbol: 'Ge', name: 'Germanium', atomicNumber: 32, mass: 72.640, category: 'nonmetal', period: 4, group: 14 },
    { id: 33, symbol: 'As', name: 'Arsenic', atomicNumber: 33, mass: 74.922, category: 'nonmetal', period: 4, group: 15 },
    { id: 34, symbol: 'Se', name: 'Selenium', atomicNumber: 34, mass: 78.960, category: 'nonmetal', period: 4, group: 16 },
    { id: 35, symbol: 'Br', name: 'Bromine', atomicNumber: 35, mass: 79.904, category: 'nonmetal', period: 4, group: 17 },
    { id: 36, symbol: 'Kr', name: 'Krypton', atomicNumber: 36, mass: 83.798, category: 'noble-gas', period: 4, group: 18 },
    { id: 37, symbol: 'Rb', name: 'Rubidium', atomicNumber: 37, mass: 85.468, category: 'metal', period: 5, group: 1 },
    { id: 38, symbol: 'Sr', name: 'Strontium', atomicNumber: 38, mass: 87.620, category: 'metal', period: 5, group: 2 },
    { id: 39, symbol: 'Y', name: 'Yttrium', atomicNumber: 39, mass: 88.906, category: 'transition-metal', period: 5, group: 3 },
    { id: 40, symbol: 'Zr', name: 'Zirconium', atomicNumber: 40, mass: 91.224, category: 'transition-metal', period: 5, group: 4 },
    { id: 41, symbol: 'Nb', name: 'Niobium', atomicNumber: 41, mass: 92.906, category: 'transition-metal', period: 5, group: 5 },
    { id: 42, symbol: 'Mo', name: 'Molybdenum', atomicNumber: 42, mass: 95.940, category: 'transition-metal', period: 5, group: 6 },
    { id: 43, symbol: 'Tc', name: 'Technetium', atomicNumber: 43, mass: 98, category: 'transition-metal', period: 5, group: 7 },
    { id: 44, symbol: 'Ru', name: 'Ruthenium', atomicNumber: 44, mass: 101.070, category: 'transition-metal', period: 5, group: 8 },
    { id: 45, symbol: 'Rh', name: 'Rhodium', atomicNumber: 45, mass: 102.906, category: 'transition-metal', period: 5, group: 9 },
    { id: 46, symbol: 'Pd', name: 'Palladium', atomicNumber: 46, mass: 106.420, category: 'transition-metal', period: 5, group: 10 },
    { id: 47, symbol: 'Ag', name: 'Silver', atomicNumber: 47, mass: 107.868, category: 'transition-metal', period: 5, group: 11 },
    { id: 48, symbol: 'Cd', name: 'Cadmium', atomicNumber: 48, mass: 112.411, category: 'transition-metal', period: 5, group: 12 },
    { id: 49, symbol: 'In', name: 'Indium', atomicNumber: 49, mass: 114.818, category: 'metal', period: 5, group: 13 },
    { id: 50, symbol: 'Sn', name: 'Tin', atomicNumber: 50, mass: 118.711, category: 'metal', period: 5, group: 14 },
    { id: 51, symbol: 'Sb', name: 'Antimony', atomicNumber: 51, mass: 121.760, category: 'nonmetal', period: 5, group: 15 },
    { id: 52, symbol: 'Te', name: 'Tellurium', atomicNumber: 52, mass: 127.600, category: 'nonmetal', period: 5, group: 16 },
    { id: 53, symbol: 'I', name: 'Iodine', atomicNumber: 53, mass: 126.904, category: 'nonmetal', period: 5, group: 17 },
    { id: 54, symbol: 'Xe', name: 'Xenon', atomicNumber: 54, mass: 131.293, category: 'noble-gas', period: 5, group: 18 },
    { id: 55, symbol: 'Cs', name: 'Cesium', atomicNumber: 55, mass: 132.906, category: 'metal', period: 6, group: 1 },
    { id: 56, symbol: 'Ba', name: 'Barium', atomicNumber: 56, mass: 137.327, category: 'metal', period: 6, group: 2 },
    { id: 57, symbol: 'La', name: 'Lanthanum', atomicNumber: 57, mass: 138.906, category: 'lanthanide', period: 6, group: 3 },
    { id: 58, symbol: 'Ce', name: 'Cerium', atomicNumber: 58, mass: 140.116, category: 'lanthanide', period: 6, group: 3 },
    { id: 59, symbol: 'Pr', name: 'Praseodymium', atomicNumber: 59, mass: 140.908, category: 'lanthanide', period: 6, group: 3 },
    { id: 60, symbol: 'Nd', name: 'Neodymium', atomicNumber: 60, mass: 144.240, category: 'lanthanide', period: 6, group: 3 },
    { id: 61, symbol: 'Pm', name: 'Promethium', atomicNumber: 61, mass: 145, category: 'lanthanide', period: 6, group: 3 },
    { id: 62, symbol: 'Sm', name: 'Samarium', atomicNumber: 62, mass: 150.360, category: 'lanthanide', period: 6, group: 3 },
    { id: 63, symbol: 'Eu', name: 'Europium', atomicNumber: 63, mass: 151.964, category: 'lanthanide', period: 6, group: 3 },
    { id: 64, symbol: 'Gd', name: 'Gadolinium', atomicNumber: 64, mass: 157.250, category: 'lanthanide', period: 6, group: 3 },
    { id: 65, symbol: 'Tb', name: 'Terbium', atomicNumber: 65, mass: 158.925, category: 'lanthanide', period: 6, group: 3 },
    { id: 66, symbol: 'Dy', name: 'Dysprosium', atomicNumber: 66, mass: 162.500, category: 'lanthanide', period: 6, group: 3 },
    { id: 67, symbol: 'Ho', name: 'Holmium', atomicNumber: 67, mass: 164.930, category: 'lanthanide', period: 6, group: 3 },
    { id: 68, symbol: 'Er', name: 'Erbium', atomicNumber: 68, mass: 167.259, category: 'lanthanide', period: 6, group: 3 },
    { id: 69, symbol: 'Tm', name: 'Thulium', atomicNumber: 69, mass: 168.934, category: 'lanthanide', period: 6, group: 3 },
    { id: 70, symbol: 'Yb', name: 'Ytterbium', atomicNumber: 70, mass: 173.040, category: 'lanthanide', period: 6, group: 3 },
    { id: 71, symbol: 'Lu', name: 'Lutetium', atomicNumber: 71, mass: 174.967, category: 'lanthanide', period: 6, group: 3 },
    { id: 72, symbol: 'Hf', name: 'Hafnium', atomicNumber: 72, mass: 178.492, category: 'transition-metal', period: 6, group: 4 },
    { id: 73, symbol: 'Ta', name: 'Tantalum', atomicNumber: 73, mass: 180.948, category: 'transition-metal', period: 6, group: 5 },
    { id: 74, symbol: 'W', name: 'Tungsten', atomicNumber: 74, mass: 183.840, category: 'transition-metal', period: 6, group: 6 },
    { id: 75, symbol: 'Re', name: 'Rhenium', atomicNumber: 75, mass: 186.207, category: 'transition-metal', period: 6, group: 7 },
    { id: 76, symbol: 'Os', name: 'Osmium', atomicNumber: 76, mass: 190.230, category: 'transition-metal', period: 6, group: 8 },
    { id: 77, symbol: 'Ir', name: 'Iridium', atomicNumber: 77, mass: 192.217, category: 'transition-metal', period: 6, group: 9 },
    { id: 78, symbol: 'Pt', name: 'Platinum', atomicNumber: 78, mass: 195.084, category: 'transition-metal', period: 6, group: 10 },
    { id: 79, symbol: 'Au', name: 'Gold', atomicNumber: 79, mass: 196.967, category: 'transition-metal', period: 6, group: 11 },
    { id: 80, symbol: 'Hg', name: 'Mercury', atomicNumber: 80, mass: 200.592, category: 'transition-metal', period: 6, group: 12 },
    { id: 81, symbol: 'Tl', name: 'Thallium', atomicNumber: 81, mass: 204.383, category: 'metal', period: 6, group: 13 },
    { id: 82, symbol: 'Pb', name: 'Lead', atomicNumber: 82, mass: 207.200, category: 'metal', period: 6, group: 14 },
    { id: 83, symbol: 'Bi', name: 'Bismuth', atomicNumber: 83, mass: 208.980, category: 'metal', period: 6, group: 15 },
    { id: 84, symbol: 'Po', name: 'Polonium', atomicNumber: 84, mass: 209, category: 'nonmetal', period: 6, group: 16 },
    { id: 85, symbol: 'At', name: 'Astatine', atomicNumber: 85, mass: 210, category: 'nonmetal', period: 6, group: 17 },
    { id: 86, symbol: 'Rn', name: 'Radon', atomicNumber: 86, mass: 222, category: 'noble-gas', period: 6, group: 18 },
    { id: 87, symbol: 'Fr', name: 'Francium', atomicNumber: 87, mass: 223, category: 'metal', period: 7, group: 1 },
    { id: 88, symbol: 'Ra', name: 'Radium', atomicNumber: 88, mass: 226, category: 'metal', period: 7, group: 2 },
    { id: 89, symbol: 'Ac', name: 'Actinium', atomicNumber: 89, mass: 227, category: 'actinide', period: 7, group: 3 },
    { id: 90, symbol: 'Th', name: 'Thorium', atomicNumber: 90, mass: 232.038, category: 'actinide', period: 7, group: 3 },
    { id: 91, symbol: 'Pa', name: 'Protactinium', atomicNumber: 91, mass: 231.036, category: 'actinide', period: 7, group: 3 },
    { id: 92, symbol: 'U', name: 'Uranium', atomicNumber: 92, mass: 238.029, category: 'actinide', period: 7, group: 3 },
    { id: 93, symbol: 'Np', name: 'Neptunium', atomicNumber: 93, mass: 237, category: 'actinide', period: 7, group: 3 },
    { id: 94, symbol: 'Pu', name: 'Plutonium', atomicNumber: 94, mass: 244, category: 'actinide', period: 7, group: 3 },
    { id: 95, symbol: 'Am', name: 'Americium', atomicNumber: 95, mass: 243, category: 'actinide', period: 7, group: 3 },
    { id: 96, symbol: 'Cm', name: 'Curium', atomicNumber: 96, mass: 247, category: 'actinide', period: 7, group: 3 },
    { id: 97, symbol: 'Bk', name: 'Berkelium', atomicNumber: 97, mass: 247, category: 'actinide', period: 7, group: 3 },
    { id: 98, symbol: 'Cf', name: 'Californium', atomicNumber: 98, mass: 251, category: 'actinide', period: 7, group: 3 },
    { id: 99, symbol: 'Es', name: 'Einsteinium', atomicNumber: 99, mass: 252, category: 'actinide', period: 7, group: 3 },
    { id: 100, symbol: 'Fm', name: 'Fermium', atomicNumber: 100, mass: 257, category: 'actinide', period: 7, group: 3 },
    { id: 101, symbol: 'Md', name: 'Mendelevium', atomicNumber: 101, mass: 258, category: 'actinide', period: 7, group: 3 },
    { id: 102, symbol: 'No', name: 'Nobelium', atomicNumber: 102, mass: 259, category: 'actinide', period: 7, group: 3 },
    { id: 103, symbol: 'Lr', name: 'Lawrencium', atomicNumber: 103, mass: 262, category: 'actinide', period: 7, group: 3 },
    { id: 104, symbol: 'Rf', name: 'Rutherfordium', atomicNumber: 104, mass: 261, category: 'transition-metal', period: 7, group: 4 },
    { id: 105, symbol: 'Db', name: 'Dubnium', atomicNumber: 105, mass: 262, category: 'transition-metal', period: 7, group: 5 },
    { id: 106, symbol: 'Sg', name: 'Seaborgium', atomicNumber: 106, mass: 266, category: 'transition-metal', period: 7, group: 6 },
    { id: 107, symbol: 'Bh', name: 'Bohrium', atomicNumber: 107, mass: 264, category: 'transition-metal', period: 7, group: 7 },
    { id: 108, symbol: 'Hs', name: 'Hassium', atomicNumber: 108, mass: 269, category: 'transition-metal', period: 7, group: 8 },
    { id: 109, symbol: 'Mt', name: 'Meitnerium', atomicNumber: 109, mass: 268, category: 'transition-metal', period: 7, group: 9 },
    { id: 110, symbol: 'Ds', name: 'Darmstadtium', atomicNumber: 110, mass: 271, category: 'transition-metal', period: 7, group: 10 },
    { id: 111, symbol: 'Rg', name: 'Roentgenium', atomicNumber: 111, mass: 272, category: 'transition-metal', period: 7, group: 11 },
    { id: 112, symbol: 'Cn', name: 'Copernicium', atomicNumber: 112, mass: 285, category: 'transition-metal', period: 7, group: 12 },
    { id: 113, symbol: 'Nh', name: 'Nihonium', atomicNumber: 113, mass: 284, category: 'metal', period: 7, group: 13 },
    { id: 114, symbol: 'Fl', name: 'Flerovium', atomicNumber: 114, mass: 289, category: 'metal', period: 7, group: 14 },
    { id: 115, symbol: 'Mc', name: 'Moscovium', atomicNumber: 115, mass: 288, category: 'metal', period: 7, group: 15 },
    { id: 116, symbol: 'Lv', name: 'Livermorium', atomicNumber: 116, mass: 292, category: 'nonmetal', period: 7, group: 16 },
    { id: 117, symbol: 'Ts', name: 'Tennessine', atomicNumber: 117, mass: 295, category: 'nonmetal', period: 7, group: 17 },
    { id: 118, symbol: 'Og', name: 'Oganesson', atomicNumber: 118, mass: 294, category: 'noble-gas', period: 7, group: 18 }
];

// Element details for the detail pages
const elementDetails = {
    1: {
        symbol: 'H',
        name: 'Hydrogen',
        atomicNumber: 1,
        mass: 1.008,
        category: 'Nonmetal',
        boilingPoint: '-252.87°C',
        meltingPoint: '-259.16°C',
        density: '0.0708 g/L',
        discovery: 'Henry Cavendish, 1766',
        uses: [
            'Fuel for rockets and hydrogen cars',
            'Production of ammonia and methanol',
            'Cooling agent for electric generators',
            'Hydrogenation of oils and fats'
        ],
        description: 'Hydrogen is the lightest and most abundant element in the universe. It is a colorless, odorless gas at room temperature and is highly flammable. Hydrogen plays a crucial role in chemistry and is the primary component of water and organic compounds.',
        electronConfiguration: '1s¹'
    },
    2: {
        symbol: 'He',
        name: 'Helium',
        atomicNumber: 2,
        mass: 4.003,
        category: 'Noble Gas',
        boilingPoint: '-268.93°C',
        meltingPoint: '-272.2°C',
        density: '0.1785 g/L',
        discovery: 'Pierre Jules Cesar Janssen, 1868',
        uses: [
            'Balloons and airships',
            'Deep sea diving (helium-oxygen mixtures)',
            'Cooling for superconducting magnets',
            'Inert atmosphere for welding'
        ],
        description: 'Helium is the second lightest element and the second most abundant in the universe after hydrogen. It is an inert noble gas that does not react with other elements. Helium is known for its unique properties, including the lowest boiling point of all elements.',
        electronConfiguration: '1s²'
    },
    3: {
        symbol: 'Li',
        name: 'Lithium',
        atomicNumber: 3,
        mass: 6.941,
        category: 'Metal',
        boilingPoint: '1342°C',
        meltingPoint: '180.5°C',
        density: '0.534 g/cm³',
        discovery: 'Johan August Arfwedson, 1817',
        uses: [
            'Rechargeable lithium batteries',
            'Aircraft and spacecraft components',
            'Psychiatric medication for bipolar disorder',
            'Heat-resistant ceramics and glass'
        ],
        description: 'Lithium is the lightest metal and the least dense of all metals. It is soft, silver-white, and highly reactive. Lithium is essential for modern technology, particularly in battery production for portable electronics and electric vehicles.',
        electronConfiguration: '[He] 2s¹'
    },
    6: {
        symbol: 'C',
        name: 'Carbon',
        atomicNumber: 6,
        mass: 12.011,
        category: 'Nonmetal',
        boilingPoint: '3825°C',
        meltingPoint: '3550°C',
        density: '2.26 g/cm³',
        discovery: 'Ancient (known since prehistoric times)',
        uses: [
            'Diamonds for industrial and decorative purposes',
            'Graphite for lubricants and pencils',
            'Steel production',
            'Fuel (coal, oil, natural gas)'
        ],
        description: 'Carbon is one of the most important elements for life. It forms the backbone of all organic molecules and exhibits multiple allotropes including diamond, graphite, and fullerenes. Carbon is unique in its ability to form long chains and complex structures.',
        electronConfiguration: '[He] 2s² 2p²'
    },
    8: {
        symbol: 'O',
        name: 'Oxygen',
        atomicNumber: 8,
        mass: 15.999,
        category: 'Nonmetal',
        boilingPoint: '-183.34°C',
        meltingPoint: '-218.3°C',
        density: '1.141 g/L',
        discovery: 'Carl Wilhelm Scheele, 1772',
        uses: [
            'Respiration (life support)',
            'Combustion and burning',
            'Production of steel',
            'Medical treatments and oxygen therapy'
        ],
        description: 'Oxygen is the third most abundant element in the universe and essential for most life forms. It is a colorless, odorless gas that readily combines with other elements. Oxygen is crucial for respiration, combustion, and water formation.',
        electronConfiguration: '[He] 2s² 2p⁴'
    },
    26: {
        symbol: 'Fe',
        name: 'Iron',
        atomicNumber: 26,
        mass: 55.845,
        category: 'Transition Metal',
        boilingPoint: '2862°C',
        meltingPoint: '1538°C',
        density: '7.874 g/cm³',
        discovery: 'Ancient (known since prehistoric times)',
        uses: [
            'Steel production',
            'Construction and infrastructure',
            'Transportation (vehicles)',
            'Machinery and tools',
            'Hemoglobin in blood (oxygen transport)'
        ],
        description: 'Iron is one of the most useful and important metals. It is the main component of steel and has been used by humans for thousands of years. Iron is magnetic and is crucial for biological functions, including oxygen transport in blood.',
        electronConfiguration: '[Ar] 3d⁶ 4s²'
    },
    79: {
        symbol: 'Au',
        name: 'Gold',
        atomicNumber: 79,
        mass: 196.967,
        category: 'Transition Metal',
        boilingPoint: '2856°C',
        meltingPoint: '1064.18°C',
        density: '19.3 g/cm³',
        discovery: 'Ancient (known since prehistoric times)',
        uses: [
            'Jewelry and decorative items',
            'Electronics and circuit boards',
            'Dentistry',
            'Medicine and radiation therapy',
            'Investment and currency'
        ],
        description: 'Gold is one of the most precious and valuable metals. It is highly resistant to corrosion and does not react with most chemicals. Gold has been prized by humans for thousands of years for its beauty, rarity, and usefulness in various applications.',
        electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹'
    }
};
